### ISSUE TITLE
feat: Add support to read provider schema from local file

### ISSUE THREAD

**Issue by tmeckel** [pulumi/registrygen#20]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

The `registrygen` tool has no option to read a provider schema JSON file from the local disk instead of downloading it from the provider repository.

This slows down the development of providers, as you always have to first upload the schema file into the provider repository in order to check the generation of the provider documentation. 

With a flag like `--useLocalSchemaFile` to the `docs` command, `registrygen` will read the file specified by the `--schemaFile` directly instead of downloading it from the repository.

**Comment by tmeckel** [comment]
I've a patched version of `registrygen` ready locally. So I could provide a PR quickly, if my feature request make sense to the Pulumi docs team.

**Comment by iwahbe** [comment]
CC @cnunciato

**Comment by iwahbe** [comment]
We are deprecating registrygen (this repo) in favor of [github.com/pulumi/registry/tools](https://github.com/pulumi/registry/pull/4663).
